# Generated by Django 4.1.5 on 2023-02-02 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='Description par defaut')),
                ('statut', models.IntegerField(default=0)),
                ('informations', models.TextField(default='Informations par defaut')),
                ('orgaId', models.IntegerField()),
                ('userAssigned', models.TextField(blank=True, null=True)),
                ('dateTimeAssigned', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.TextField(unique=True)),
                ('typeEvent', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('lieu', models.TextField(blank=True)),
                ('date', models.DateField(blank=True)),
                ('horaire', models.TextField(blank=True)),
                ('tarifs', models.TextField(blank=True)),
                ('toDo', models.ManyToManyField(to='organizeEvent.todo')),
            ],
        ),
    ]
