# Generated by Django 4.1.5 on 2023-01-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('isChecked', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeEvent', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('lieu', models.TextField(blank=True)),
                ('date', models.TextField(blank=True)),
                ('horaire', models.TextField(blank=True)),
                ('tarifs', models.TextField(blank=True)),
                ('toDo', models.ManyToManyField(to='organizeEvent.todo')),
            ],
        ),
    ]
