# Generated by Django 4.1.5 on 2023-02-06 14:50

from django.db import migrations, models
import organizeEvent.validators


class Migration(migrations.Migration):

    dependencies = [
        ('organizeEvent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comptabilite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('source', models.TextField(blank=True)),
                ('label', models.TextField(blank=True)),
                ('paiementType', models.TextField()),
                ('isPositive', models.BooleanField()),
                ('note', models.TextField(blank=True, null=True)),
                ('requestToken', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='organisation',
            name='password',
            field=models.TextField(unique=True, validators=[organizeEvent.validators.validate_password]),
        ),
        migrations.AlterField(
            model_name='todo',
            name='userAssigned',
            field=models.TextField(blank=True, null=True, validators=[organizeEvent.validators.validate_username]),
        ),
    ]
