# Generated by Django 4.1.5 on 2023-01-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizeEvent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='isChecked',
            field=models.BooleanField(default=False),
        ),
    ]
