# Generated by Django 4.1.5 on 2023-01-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizeEvent', '0002_alter_todo_ischecked'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='orgaId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
