# Generated by Django 4.1.5 on 2023-02-07 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizeEvent', '0003_comptabilite_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comptabilite',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
