# Generated by Django 4.1.5 on 2023-01-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizeEvent', '0003_todo_orgaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='informations',
            field=models.TextField(default='Informations par defaut'),
        ),
    ]
