# Generated by Django 4.1.5 on 2023-01-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizeEvent', '0006_alter_todo_userassigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='userAssigned',
            field=models.TextField(blank=True, null=True),
        ),
    ]
