# Generated by Django 4.1.5 on 2023-01-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizeEvent', '0007_alter_todo_userassigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
