# Generated by Django 4.1.5 on 2023-01-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizeEvent', '0008_alter_organisation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='dateTimeAssigned',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
